services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz.exercise.com
    command: npm start
    volumes:
      - node_modules:/app/node_modules
      - ./app:/app
    ports:
      - "9000:9000"
      
volumes:
  node_modules: